# <u><b>Data Transformation & Features Engineering</b></u>

## <b style='color: yellow;'>0.</b> <u>Import Libraries</u>

In [1]:
import csv
import numpy as np
import pandas as pd
import openpyxl as op

# Force pandas to print all columns in a single line.
pd.set_option('display.width', 1000)                # Keeps lines from wrapping.
pd.set_option('display.max_columns', None)          # Displays every single column.

## <u>Load the data</u>

In [2]:
# Load the 'Cleaned_Sales.xlsx' using pandas.
df = pd.read_excel('./excel/Cleaned_sales.xlsx')
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0

[265120 rows x 16 columns]

---

## <b style='color: yellow;'>2.</b> <u>Data Transformation & Feature Engineering</u>

<ul style='font-size: 1.4em; line-height: 1.4;'>
    <li><b style='color: red;'>Step 2.0.</b> <b> Remove Rows That 'Quantity' is Zero</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Since the 'Quantity' is zero, we can remove and neglect analysis this part. Because, it we won't gain any benefits from analyzing the empty 'Quantity'.</p>
    </li>
    <li><b style='color: red;'>Step 2.1.</b> <b> Add Columns That Is Related to Time</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">For the most effective and most efficient AI modelling of the <mark><b>Time-Series Analysis</b></mark>. We want attributes that is related to the day, the week, the month, or the year, as much as possible.</p>
            <ol style='line-height: 1.4;'>
                <li><b style = 'color: orange;'>Step 2.1.1.</b><b> Adding 'Year' and 'Month'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Year</b></mark> & <mark><b>Month</b></mark> column using <mark><b>dt.year</b></mark> & <mark><b>dt.month</b></mark> to captures long-term annual growth trends and monthly seasonal patterns.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.1.2.</b><b> Adding 'Quarter'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Quarter</b></mark> using <mark><b>dt.quarter</b></mark> breakdown the months into quarter. To see seasonal changes in sales volume.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.1.3.</b><b> Adding 'is_month_end' and 'is_quarter_end'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>is_month_end</b></mark> and <mark><b>is_quarter_end</b></mark> using <mark><b>dt.is_month_end</b></mark> and <mark><b>is_quarter_end</b></mark> respectively. To identifies sales surges caused by quarterly quotas or end-of-financial-period pushes.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.1.4.</b><b> Adding 'Day of Week'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Day of Week</b></mark> using <mark><b>dt.dayofweek</b></mark> uncovers weekly order patterns. (e.g., weekday bulk ordering vs. weekend ordering).</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.1.5.</b><b> Adding 'is_weekend'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>is_weekend</b></mark> using <mark><b>dt.dayofweek >= 5</b></mark> to add a binary flag to separate business-day sales from weekend or holiday activity.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.1.6.</b><b> Adding 'Day of Month'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Day of Month</b></mark> using <mark><b>dt.day</b></mark> to helps capture end-of-month or beginning-of-month purchasing spikes (common in B2B corporate budget cycles).</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.1.7.</b><b> Adding 'Year-Month'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Year-Month</b></mark> using <mark><b>dt.to_period('M')</b></mark> for grouping and aggregating monthly sales trends, and building rolling averages.</p>
                </li>
            </ol>
    </li>
    <li><b style='color: red;'>Step 2.2.</b> <b> Add Columns That Is Related to Financial </b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Since we are going to analyze and forecast or predict about the sales we need to create other attributes related to sales wise.</p>
            <ol style='line-height: 1.4;'>
                <li><b style = 'color: orange;'>Step 2.2.1.</b><b> Add 'Total Sales Amount'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Add the <mark><b>Total Sales Amount</b></mark> to see the revenue of each row. <mark><b>Total Sales Amount = Quantity * Base Price</b></mark>.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.2.</b><b> Add 'Discount Amount'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Some of the 'Base Price' is less than the 'List Price', this could mean that the the customer received a discount. The column will determine the amount of discount received, <mark><b>Discount Amount = List Price - Base Price</b></mark>.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.3.</b><b> Add 'Discount Percentage'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">'Discount Amount' turned to a Percentage for visualization. <mark><b>Discount Percentage = ((List Price - Base Price) / List Price) * 100</b></mark>.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.4.</b><b> Add 'Total Gross Value (Expected Revenue Before Discount)'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Total Gross Value = Quantity * List Price</b></mark> will represents the maximum revenue potential of an order before any pricing negotiations or promotional discounts are applied. Comparing this against <mark><b>Total Sales Amount</b></mark> gives executive leadership an immediate view of total top-line revenue leakage.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.5.</b><b> Add 'Total Discount Value (Row-Level Revenue Loss)'</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Total Discount Value = Quantity * Discount Amount</b></mark>. While 'Discount Amount' measures unit-level price cuts, 'Total Discount Value' scales it by order size. For example a 5 Baht discount on 1000 units is 5000 Baht loss, is financially more critical than a 100 Baht discount on 1 unit which is 100 Baht loss.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.6.</b><b> Unit Selling Price (Effective Price)</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Unit Selling Price = Total Sales Amount/Quantity (or simply Base Price)</b></mark>. Useful for tracking price elasticity. In complex B2B sales, tier-discounting often lowers the unit price as purchase volumes increase</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.7.</b><b> Tiered Order Value Category (Order Size Bins)</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Categorize <mark><b>Total Sales Amount</b></mark> into business tiers (e.g. Small: < 1000 Baht, Medium: 1000 Baht - 10,000 Baht, Large: 10,000 Baht - 50,000 Baht, Enterprise: > 50,000 Baht). Machine learning models (like <mark><b>Random Forests</b></mark> or <mark><b>Gradient Boosting)</b></mark> benefit from categorical order size flags when predicting customer behavior, as high-value enterprise accounts follow very different purchase cycles than small accounts.</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.8.</b><b> Historical Revenue Features (Customer LTV (Customer Lifetime Value) & Average Order Value)</b>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Customer spending power is one of the strongest predictive signals for future sales forecasting.</p>
                        <ul style='line-height: 1.4;'>
                            <p style='font-size: 1em; margin-top: 8px; line-height: 1.4;'><b>Features to Aggregate:</b></p>
                            <li><mark><b>Customer Cumulative Revenue</b></mark>: Running total of revenue generated by a customer up to the transaction date.
                            </li>
                            <li><mark><b>Customer Average Order Value (AOV)</b></mark>: Mean <mark><b>Total Sales Amount</b></mark> per order for each specific customer.
                            </li>
                        </ul>
                </li>
                <li><b style = 'color: orange;'>Step 2.2.9.</b><b> Pricing Variance / Discount Flag</b>
                    <ul style='line-height: 1.4;'><b>Formula:</b>
                        <li><mark><b>Is_Discounted</b></mark>: Binary flag (1 = Discount Amount > 0, else 0).</li>
                        <li><mark><b>Is_Zero_Base_Price</b></mark>: Binary flag (1 = Base Price is 0, else 0, representing promotional bundles/free samples/ negotiating price).</li>
                    </ul>
                    <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Helps Machine Learning models to instantly separate standard commercial transactions from promotional, bundled, or warranty replacement items.</p>
                </li>
            </ol>
    </li>
    <li><b style='color: red;'>Step 2.3.</b> <b> Add Column of Refined the 'Sale Order Status' Column</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">Because currently there are 6 values; 'Billed', 'Closed', 'Partially Fulfilled', 'Pending Fulfillment', 'Pending Billing', 'Pending Billing/Partially Fulfilled'. We will group the pending transaction to a new value called 'In-Pipeline', which indicates unconfirmed transaction for easier analysis.</p>
    </li>
    <li><b style='color: red;'>Step 2.4.</b> <b> Adding 'Day Since Last Purchase' Column</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">in B2B industrial automation, customer reordering habits are periodic. A sudden spike in purchase interval often signals customer churn or vendor switching. This column will indicate the number of days between a customer's current order.</p>
    </li>
    <li><b style='color: red;'>Step 2.5.</b> <b> Adding 'Product-Level Demand'</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Item Historical Average Demand</b></mark>: Average quantity sold per transaction for each product <mark><b>Item Code</b></mark>.<br><mark><b>Item Price Elasticity Ratio: Base Price / Mean Item Base Price</b></mark> This indicates whether this specific sales was discounted relative to how the item is usually sold across all customer.<br>Because Tree-based models (like XGBoost or LightGBM) struggle to learn baseline demand purely from raw categorical IDs, Group-level aggregations provide direct price sensitivity signals.</p>
    </li>
    <li><b style='color: red;'>Step 2.6.</b> <b> Customer Product Diversity (Behavioral Signal)</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><mark><b>Customer Unique Item Count</b></mark>: Total number of distinct <mark><b>Item Code</b></mark> types of customer buys over time. VIP clients purchase across multiple product lines (PLCs, Servo, Drives, HMIs), whereas one-off buyers purchase single replacement components.</p>
    </li>
    <li><b style='color: red;'>Step 2.7.</b> <b> Cyclical Encoding for Time Features (For Neural Networks/ Linear Models)</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;"><b>Features</b>: Sine/ Cosine transformations of <mark><b>Month</b></mark>: 1-12 and <mark><b>Day of Week</b><mark>: 0-6. Algorithms like Linear Regression or Neural Networks see <mark><b>Month 12</b></mark> (December) and <mark><b>Month 1</b></mark> (January) as far apart, even though they are adjacent in time. Cyclical sine/ cosine transformation preserves continuous calendar cycles</p>
    </li>
    <li><b style='color: red;'>Step 2.8.</b> <b> Inventory Management Features</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">You can calculate inventory management metrics per item based on the latest transaction date in the dataset (2025-03-31):</p>
        <ol style='line-height: 1.4;'>
                <li><b style = 'color: orange;'>Step 2.8.1.</b><mark><b>Day Since Last Sale </b></mark>
                    <p>(Max_Dataset_Date) - (Last_Item_Sale_Date)</p>
                </li>
                <li><b style = 'color: orange;'>Step 2.8.2.</b><mark><b>Inventory Velocity Status</b></mark>, Categorize items into turnover tiers:</b></li>
                    <ul style='line-height: 1.4;'>
                        <li><b>Fast Moving</b>: Sold within the last 90 days (less than 0.25 years).</li>
                        <li><b>Slow Moving</b>: Last sold 1 to 2 years ago.</li>
                        <li><b>At-Risk / Aging</b>: Last sold 2 to 3.5 years ago.</li>
                        <li><b>Obsolete / Dead Stock Risk</b>: Last sold more than 3.5 years ago (or items marked as <mark><b>Discontinue</b></mark> in <mark><b>Production Status</b></mark>).
                    </ul>
            </ol>
    </li>
    <li><b style='color: red;'>Step 2.9.</b> <b> Dealing with Outliers</b>
        <p style='font-size: 1em; margin-top: 8px; line-height: 1.4;'>We are dealing with the outliers later. Because, 1. We Need Raw Totals for Financial Accuracy, 2. Some Features Help Identify Real vs. Fake Outliers, 3. Capping is Better than Removing the outliers.</p>
    </li>
    <li><b style='color: red;'>Step 2.10.</b> <b> Save to a New Excel</b></li>
</ul>

---

<p style='font-size: 1.4em;'><u><b style='color: red'>Step 2.0.</b> <b>Remove Rows That 'Quantity' is Zero</u></b>

In [3]:
# Remove any rows where the 'Quantity' is less than or equal to zero.
df = df[df['Quantity'] > 0]
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0

[265070 rows x 16 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.1.</b><b> Add Columns That Is Related to Time</b></u></p>

In [4]:
# Force Pandas to recognize the 'Sale Order Date' column as a datetime object for pandas to do further analysis.
df['Sales Order Date'] = pd.to_datetime(df['Sales Order Date'])

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.1.</b><b> Adding 'Year' and 'Month'</b></u></p>

In [5]:
# Add column 'Year' and 'Month'.
# 1) Adding the 'Year' column.
df['Year'] = df['Sales Order Date'].dt.year

# 2) Adding the 'Month' column.
df['Month'] = df['Sales Order Date'].dt.month
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3

[265070 rows x 18 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.2.</b><b> Adding 'Quarter'</b></u></p>

In [6]:
# Adding the 'Quarter' column.
df['Quarter'] = df['Sales Order Date'].dt.quarter
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1

[265070 rows x 19 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.3.</b><b> Adding 'is_month_end' and 'is_quarter_end'</b></u></p>

In [7]:
# Adding column 'is_month_end' and 'is_quarter_end'.
# 1) Adding the 'is_month_end' column.
df['is_month_end'] = df['Sales Order Date'].dt.is_month_end

# 2) Adding the 'is_quarter_end' column.
df['is_quarter_end'] = df['Sales Order Date'].dt.is_quarter_end
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False

[265070 rows x 21 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.4.</b><b> Adding 'Day of Week'</b></u></p>

In [8]:
# Adding the 'Day of Week' column.
df['Day of Week'] = df['Sales Order Date'].dt.day_of_week
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4

[265070 rows x 22 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.5.</b><b> Adding 'is_weekend'</b></u></p>

In [9]:
# Adding the 'is_weekend' column.
df['is_weekend'] = df['Sales Order Date'].dt.day_of_week >= 5
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False

[265070 rows x 23 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.6.</b><b> Adding 'Day of Month'</b></u></p>

In [10]:
# Adding the 'Day of Month' column.
df['Day of Month'] = df['Sales Order Date'].dt.day
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28

[265070 rows x 24 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.1.7.</b><b> Adding 'Year-Month'</b></u></p>

In [11]:
# Adding 'Year-Month' column.
df['Year-Month'] = df['Sales Order Date'].dt.to_period('M')
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03

[265070 rows x 25 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.2.</b><b> Add Columns That Is Related to Financial</b></u></p>

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.1.</b><b> Add 'Total Sales Amount'</b></u></p>

In [12]:
# Adding 'Total Sales Amount' column.
df['Total Sales Amount'] = df['Quantity'] * df['Base Price']
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0

[265070 rows x 26 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.2.</b><b> Add 'Discount Amount'</b></u></p>

In [13]:
# Adding 'Discount Amount' column, don't multiply with a 100 yet.
df['Discount Amount'] = df['List Price'] - df['Base Price']
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0           2010.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0           2235.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0            195.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0           3690.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0           2294.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0           1241.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0              0.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0          -7086.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0              0.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0           1416.0

[265070 rows x 27 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.3.</b><b> Add 'Discount Percentage'</b></u></p>

In [14]:
# Adding 'Discount Percentage' column.
df['Discount Percentage'] = (df['Discount Amount'] / df['List Price'])
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0           2010.0             0.122293
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0           2235.0             0.123066
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0            195.0             0.077350
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0           3690.0             0.125870
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0           2294.0             0.126600
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0           1241.0             0.084496
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0              0.0             0.000000
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0          -7086.0            -6.906433
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0              0.0             0.000000
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0           1416.0             0.085342

[265070 rows x 28 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.4.</b><b> Add 'Total Gross Value' (Expected Revenue Before Discount)</b></u></p>

In [15]:
# Adding 'Total Gross Value' column.
df['Total Gross Value'] = df['Quantity'] * df['List Price']
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0           2010.0             0.122293            16436.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0           2235.0             0.123066            18161.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0            195.0             0.077350             2521.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0           3690.0             0.125870            29316.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0           2294.0             0.126600            18120.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0           1241.0             0.084496            29374.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0              0.0             0.000000            37073.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0          -7086.0            -6.906433             2052.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0              0.0             0.000000            28953.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0           1416.0             0.085342            16592.0

[265070 rows x 29 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.5.</b><b> Add 'Total Discount Value' (Row-Level Revenue Loss)</b></u></p>

In [16]:
# Adding 'Total Discount Value' column.
df['Total Discount Value'] = df['Quantity'] * df['Discount Amount']
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0           2010.0             0.122293            16436.0                2010.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0           2235.0             0.123066            18161.0                2235.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0            195.0             0.077350             2521.0                 195.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0           3690.0             0.125870            29316.0                3690.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0           2294.0             0.126600            18120.0                2294.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0           1241.0             0.084496            29374.0                2482.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0              0.0             0.000000            37073.0                   0.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0          -7086.0            -6.906433             2052.0              -14172.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0              0.0             0.000000            28953.0                   0.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0           1416.0             0.085342            16592.0                1416.0

[265070 rows x 30 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.6.</b><b> Unit Selling Price (Effective Price)</b></u></p>

In [17]:
# Adding 'Unit Selling Price' column.
df['Unit Selling Price'] = df['Total Sales Amount'] / df['Quantity']
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0           2010.0             0.122293            16436.0                2010.0             14426.0
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0           2235.0             0.123066            18161.0                2235.0             15926.0
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0            195.0             0.077350             2521.0                 195.0              2326.0
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0           3690.0             0.125870            29316.0                3690.0             25626.0
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0           2294.0             0.126600            18120.0                2294.0             15826.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0           1241.0             0.084496            29374.0                2482.0             13446.0
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0              0.0             0.000000            37073.0                   0.0             37073.0
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0          -7086.0            -6.906433             2052.0              -14172.0              8112.0
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0              0.0             0.000000            28953.0                   0.0             28953.0
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0           1416.0             0.085342            16592.0                1416.0             15176.0

[265070 rows x 31 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.7.</b><b> Tiered Order Value Category (Order Size Bins)</b></u></p>

In [18]:
# Define thresholds from bin labels.
bins = [-np.inf, 1000, 10_000, 50_000, np.inf]          # in Baht.
labels = ['Small (<1k)', 'Medium (1k-10k)', 'Large (10k-50k)', 'Enterprise (>50k)']

# Create the categorical order size feature
df['Order Size Tier'] = pd.cut(df['Total Sales Amount'], bins=bins, labels=labels)
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type           Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price  Order Size Tier
0              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8523       CFN     14426.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     16436.0  2021      4        2         False           False            3       False             1    2021-04             14426.0           2010.0             0.122293            16436.0                2010.0             14426.0  Large (10k-50k)
1              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8533       CFY     15926.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     18161.0  2021      4        2         False           False            3       False             1    2021-04             15926.0           2235.0             0.123066            18161.0                2235.0             15926.0  Large (10k-50k)
2              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.             20142       CGX      2326.0         1           VIP  Wholesale and Distribution          Continue                INV         INV Others      2521.0  2021      4        2         False           False            3       False             1    2021-04              2326.0            195.0             0.077350             2521.0                 195.0              2326.0  Medium (1k-10k)
3              7165143       2021-04-01               AAAA             Billed                  5356  AAH CO.,LTD.              8552       CGL     25626.0         1           VIP  Wholesale and Distribution       Discontinue                INV    INV E700 Nagoya     29316.0  2021      4        2         False           False            3       False             1    2021-04             25626.0           3690.0             0.125870            29316.0                3690.0             25626.0  Large (10k-50k)
4              7165145       2021-04-01               AAAB             Billed                  5356  AAH CO.,LTD.             24548       CXR     15826.0         1           VIP  Wholesale and Distribution          Continue                PLC             PLC FX     18120.0  2021      4        2         False           False            3       False             1    2021-04             15826.0           2294.0             0.126600            18120.0                2294.0             15826.0  Large (10k-50k)
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...                         ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...              ...
265115         9741141       2025-03-31               GQRI             Billed                  4620  AAA CO.,LTD.              8357       CBU     13446.0         2           VIP  Wholesale and Distribution     To Be Advised                INV    INV D700 Nagoya     14687.0  2025      3        1          True            True            0       False            31    2025-03             26892.0           1241.0             0.084496            29374.0                2482.0             13446.0  Large (10k-50k)
265116         9741143       2025-03-31               GQRJ             Billed                  4743  AAD CO.,LTD.             62016       DHB     37073.0         1           VIP  Wholesale and Distribution          Continue                PLC          PLC iQ-FX     37073.0  2025      3        1          True            True            0       False            31    2025-03             37073.0              0.0             0.000000            37073.0                   0.0             37073.0  Large (10k-50k)
265117         9749770       2025-03-30               GQRK             Billed                  1552  AEH CO.,LTD.            323027       DMV      8112.0         2      End User                       Other          Continue       Geared Motor       Geared Motor      1026.0  2025      3        1         False           False            6        True            30    2025-03             16224.0          -7086.0            -6.906433             2052.0              -14172.0              8112.0  Large (10k-50k)
265118         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             70605       EAQ     28953.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     28953.0  2025      3        1         False           False            4       False            28    2025-03             28953.0              0.0             0.000000            28953.0                   0.0             28953.0  Large (10k-50k)
265119         9750154       2025-03-28               GQRL             Closed                 10055  BLE CO.,LTD.             67874       EAL     15176.0         1      End User                       Paper          Continue                HMI     GOT2000 Himeji     16592.0  2025      3        1         False           False            4       False            28    2025-03             15176.0           1416.0             0.085342            16592.0                1416.0             15176.0  Large (10k-50k)

[265070 rows x 32 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.8.</b><b> Historical Revenue Features (Customer LTV (Customer Lifetime Value) & Average Order Value)</b></u></p>

<p style='font-size: 1.4em; l'><b>A. Cumulative Revenue (Customer Lifetime Value to Date)</b></p>
<p style='font-size: 1.4em; l'>Calculates the total revenue a customer has generated up to (and including) each transaction:</p>

In [19]:
# Sort by customer and date to maintain chronological order.
df = df.sort_values(by=['Customer Internal Id', 'Sales Order Date'])

# Calculate cumulative historical revenue per customer.
df['Customer Cumulative Revenue'] = df.groupby('Customer Internal Id')['Total Sales Amount'].cumsum()
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue
129727         8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0
129728         8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0
169102         8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0
7014           7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0
7015           7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...
255691         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0
255692         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0
257580         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0
258464         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0
259777         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0

[265070 rows x 33 columns]

<p style='font-size: 1.4em; l'><b>B. Customer Average Order Value (AOV)</b></p>
<p style='font-size: 1.4em; l'>Calculates the historical average spend per transaction for each customer up to that point in time:</p>

In [20]:
# Calculate cumulative order count per customer.
df['Customer Order Count'] = df.groupby('Customer Internal Id').cumcount() + 1

# Calculate expanding Average Order Value (AOV).
df['Customer AOV'] = df['Customer Cumulative Revenue'] / df['Customer Order Count']
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV
129727         8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0
129728         8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5
169102         8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0
7014           7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0
7015           7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...
255691         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0
255692         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0
257580         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0
258464         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0
259777         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0

[265070 rows x 35 columns]

<p style='font-size: 1.4em; l'><b>C. Overall Customer Lifetime Value (Static Snapshot)</b></p>
<p style='font-size: 1.4em; l'>To determine a single total summary metric per customer across the whole dataset (for segmentation rather than time-series forecasting)</p>

In [21]:
# Total LTV snapshot.
customer_ltv = df.groupby('Customer Internal Id')['Total Sales Amount'].sum().rename('Customer Total LTV')
df = df.merge(customer_ltv, on='Customer Internal Id', how='left')
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0

[265070 rows x 36 columns]

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.2.9.</b><b> Pricing Variance / Discount Flag</b></u></p>

<p style='font-size: 1.4em; l'><b>1. Is_Discounted</b></p>
<p style='font-size: 1.4em; l'>Binary flag: 1 = Discounted Amount > 0, 0 = Else.</p>

In [22]:
# Add 'is_discounted' column.
df['is_discounted'] = df['Discount Amount'] > 0
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False

[265070 rows x 37 columns]

<p style='font-size: 1.4em; l'><b>2. Is_Zero_Base_Price</b></p>
<p style='font-size: 1.4em; l'>Binary flag: 1 = Base Price is 0, 0 = Else. Representing promotional bundles/ free samples/ negotiating price.</p>

In [23]:
# Add 'is_zero_base_price' column.
df['is_zero_base_price'] = df['Base Price'] == 0
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False

[265070 rows x 38 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.3.</b><b> Add Column of Refined the 'Sale Order Status' Column</b></u></p>

<p style='font-size: 1.4em;'>To simplify these 6 status for business logic or to have a simplified values. We can group these 6 values into the following table:</p>

| Simplified | Included System Status | Financial Meaning |
| :--- | :--- | :--- |
| Recognized / Billed Revenue | Billed | Invoiced and official income |
| Unbilled / Earned Pipeline | Pending Billing, Pending Billing/Partially Fulfilled | Work/goods delivered, pending invoice. Safe to count as projected income |
| Unearned / Open Backlog | Pending Fulfillment, Partially Fulfilled, Closed | Future potential sales, Unfulfilled items, or canceled orders. Do not count as income |

In [24]:
# Define matching condition.
earned = df['Sales Order Status'].isin(['Billed'])
on_going = df['Sales Order Status'].isin(['Pending Billing', 'Pending Billing/Partially Fulfilled'])
loss = df['Sales Order Status'].isin([
    'Pending Fulfillment',
    'Partially Fulfilled',
    'Closed'
])

conditions = [earned, on_going, loss]
choices = ['Earned', 'On going', 'Loss']

# Apply Mapping.
df['Sales Order Status Group'] = np.select(conditions, choices, default='Other')
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned

[265070 rows x 39 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.4.</b><b> Adding 'Day Since Last Purchase Column'</b></u></p>

In [25]:
df = df.sort_values(['Customer Internal Id', 'Sales Order Date'])

# Days elapsed since previous order for each customer.
df['Days Since Last Purchase'] = (
    df.groupby('Customer Internal Id')['Sales Order Date'].diff().dt.days.fillna(0)
)
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0

[265070 rows x 40 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.5.</b><b> Adding 'Product-Level Demand'</b></u></p>

<p style='font-size: 1.4em; l'><b>1. Item Historical Average Demand (Mean quantity sold per order for each SKU).</b></p>

In [26]:
# Mean quantity sold per order for each SKU.
df['Product-Level Demand'] = df.groupby('Item Code')['Quantity'].transform('mean')
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0              1.272966
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0              5.454545
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0              1.240566
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0              2.635659
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0              6.283388
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0              2.038610
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0              1.293750
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0              1.354167
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0              1.090909
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0              5.587687

[265070 rows x 41 columns]

<p style='font-size: 1.4em; l'><b>2. Item Price Elasticity Ratio (Actual Base Price relative to the item's global mean price).</b></p>

In [27]:
item_mean_price = df.groupby('Item Code')['Base Price'].transform('mean')
df['Item Price Elasticity Ratio'] = np.where(item_mean_price > 0, df['Base Price'] / item_mean_price, 1.0)
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0              1.272966                     1.099698
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0              5.454545                     0.854174
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0              1.240566                     1.088854
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0              2.635659                     0.979929
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0              6.283388                     1.033099
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0              2.038610                     1.224468
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0              1.293750                     1.130720
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0              1.354167                     1.104637
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0              1.090909                     1.038609
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0              5.587687                     1.059810

[265070 rows x 42 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.6.</b><b> Customer Product Diversity (Behavioral Signal)</b></u></p>

<p style='font-size: 1.4em; l'><b>1. Customer Unique Item Count (Cumulative count of distinct items bought up to that order date).</b></p>

In [28]:
df['Customer Unique Item Count'] = (
    df.groupby('Customer Internal Id')['Item Code'].transform(lambda x: (~x.duplicated()).cumsum())
)
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0              1.272966                     1.099698                           1
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0              5.454545                     0.854174                           2
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0              1.240566                     1.088854                           3
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0              2.635659                     0.979929                           1
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0              6.283388                     1.033099                           2
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...                         ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0              2.038610                     1.224468                           2
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0              1.293750                     1.130720                           3
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0              1.354167                     1.104637                           1
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0              1.090909                     1.038609                           1
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0              5.587687                     1.059810                           1

[265070 rows x 43 columns]

<p style='font-size: 1.4em; l'><b>2. Total unique items ever purchased by the customer across all history.</b></p>

In [29]:
customer_total_unique = df.groupby('Customer Internal Id')['Item Code'].transform('nunique')
df['Customer Total Unique Items Overall'] = customer_total_unique
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count  Customer Total Unique Items Overall
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0              1.272966                     1.099698                           1                                    3
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0              5.454545                     0.854174                           2                                    3
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0              1.240566                     1.088854                           3                                    3
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0              2.635659                     0.979929                           1                                   12
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0              6.283388                     1.033099                           2                                   12
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...                         ...                                  ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0              2.038610                     1.224468                           2                                    3
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0              1.293750                     1.130720                           3                                    3
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0              1.354167                     1.104637                           1                                    1
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0              1.090909                     1.038609                           1                                    1
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0              5.587687                     1.059810                           1                                    1

[265070 rows x 44 columns]

<p style='font-size: 1.4em;'><b style='color: Green;'><u>NOTE!</u></b></p>
<ol style='font-size: 1.4em; line-height: 1.4;'>
    <li><mark><b>Item Historical Average Demand</b></mark>: Gives tree-based models (like XGBoost) a continuous signal of how fast an item moves on average without needing high-cardinality one0hot encoding on raw SKU rating.</li>
    <li><mark><b>Item Price Elasticity Ratio</b></mark>: Signals pricing variation. A value < 1.0 indicates the item was sold at a discount relative to its normal average market price, where as > 1.0 indicates a premium charge.</li>
    <li><mark><b>Customer Unique Item Count</b></mark>: Measures account breadth over time. Customers with high item diversity buy across whole product portfolios (e.g., PLCs, Servos, HMIs) and have lower churn rates compared to single-item buyers.</li>
</oi>

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.7.</b><b> Cyclical Encoding for Time Features (For Neural Networks/ Linear Models)</b></u></p>

In [30]:
# Adding 'Sin_Month' and 'Cos_Month' columns.
df['sin_month'] = np.sin(2 * np.pi * df['Month'] / 12)
df['cos_month'] = np.cos(2 * np.pi * df['Month'] / 12)
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count  Customer Total Unique Items Overall     sin_month     cos_month
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0              1.272966                     1.099698                           1                                    3 -2.449294e-16  1.000000e+00
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0              5.454545                     0.854174                           2                                    3 -2.449294e-16  1.000000e+00
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0              1.240566                     1.088854                           3                                    3 -8.660254e-01 -5.000000e-01
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0              2.635659                     0.979929                           1                                   12  5.000000e-01 -8.660254e-01
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0              6.283388                     1.033099                           2                                   12  5.000000e-01 -8.660254e-01
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...                         ...                                  ...           ...           ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0              2.038610                     1.224468                           2                                    3  8.660254e-01  5.000000e-01
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0              1.293750                     1.130720                           3                                    3  8.660254e-01  5.000000e-01
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0              1.354167                     1.104637                           1                                    1  8.660254e-01  5.000000e-01
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0              1.090909                     1.038609                           1                                    1  8.660254e-01  5.000000e-01
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0              5.587687                     1.059810                           1                                    1  1.000000e+00  6.123234e-17

[265070 rows x 46 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.8.</b><b> Inventory Management Features</b></u></p>

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.8.1.</b><b> 'Day Since Last Sale' Column</b></u></p>

In [31]:
# Add Reference date (latest transaction in dataset).
ref_date = df['Sales Order Date'].max()

# Aggregate metrics at Item Level.
inventory_features = df.groupby(['Item Internal Id', 'Item Code']).agg(
    Last_Sale_Date=('Sales Order Date', 'max'),
    First_Sale_Date=('Sales Order Date', 'min'),
    Total_Unit_Sold=('Quantity', 'sum'),
    Total_Revenue=('Total Sales Amount', 'sum'),
    Order_Count=('So Internal Id', 'count')
).reset_index()

# Calculate Age & Inactivity Features.
inventory_features['Days_Since_Last_Sale'] = (ref_date - inventory_features['Last_Sale_Date']).dt.days
inventory_features['Years_Inactive'] = inventory_features['Days_Since_Last_Sale'] / 365.25

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 2.8.2.</b><b> Inventory Velocity Status</b></u></p>

In [32]:
def categorize_velocity(years):
    if years < 0.25:
        return 'Fast Moving (<3 Months)'
    elif years < 1.0:
        return 'Normal Velocity (3-12 Months)'
    elif years < 2.0:
        return 'Slow Moving (1-2 yrs)'
    elif years < 3.5:
        return 'High Aging Risk (2-3.5 yrs)'
    else:
        return 'Critical Risk! (>3.5 years)'

#
inventory_features['Inventory_Risk_Tier'] = inventory_features['Years_Inactive'].apply(categorize_velocity)

# Calculate total active days (clipping at minimum 1 to prevent division by zero)
inventory_features['Days_Active'] = (ref_date - inventory_features['First_Sale_Date']).dt.days.clip(lower=1)

# 1. Units sold per active day (Unit Velocity)
inventory_features['Sales_Frequency_Ratio_Units'] = inventory_features['Total_Unit_Sold'] / inventory_features['Days_Active']

# 2. Orders per active day (Order Velocity)
inventory_features['Sales_Frequency_Ratio_Orders'] = inventory_features['Order_Count'] / inventory_features['Days_Active']
inventory_features

      Item Internal Id Item Code Last_Sale_Date First_Sale_Date  Total_Unit_Sold  Total_Revenue  Order_Count  Days_Since_Last_Sale  Years_Inactive          Inventory_Risk_Tier  Days_Active  Sales_Frequency_Ratio_Units  Sales_Frequency_Ratio_Orders
0                  111       AYV     2023-12-25      2023-11-22                3       12002.25            2                   462        1.264887        Slow Moving (1-2 yrs)          495                     0.006061                      0.004040
1                 2659       FXK     2022-10-04      2022-05-31                2       80652.00            2                   909        2.488706  High Aging Risk (2-3.5 yrs)         1035                     0.001932                      0.001932
2                 6199       FFU     2025-03-31      2021-04-02            11999    20535581.42          806                     0        0.000000      Fast Moving (<3 Months)         1459                     8.224126                      0.552433
3                 6200       FFZ     2025-03-03      2021-04-09              176      378297.00           90                    28        0.076660      Fast Moving (<3 Months)         1452                     0.121212                      0.061983
4                 6201       FGF     2025-03-26      2021-04-05              251     1361959.60          106                     5        0.013689      Fast Moving (<3 Months)         1456                     0.172390                      0.072802
...                ...       ...            ...             ...              ...            ...          ...                   ...             ...                          ...          ...                          ...                           ...
5688            368917       CJY     2025-03-17      2025-03-17                2      110084.00            1                    14        0.038330      Fast Moving (<3 Months)           14                     0.142857                      0.071429
5689            369018       CJN     2025-03-18      2025-03-18                1       35729.00            1                    13        0.035592      Fast Moving (<3 Months)           13                     0.076923                      0.076923
5690            369829       CJI     2025-03-18      2025-03-18                1       16380.00            1                    13        0.035592      Fast Moving (<3 Months)           13                     0.076923                      0.076923
5691            370438       CCV     2025-03-18      2025-03-18                1       17811.00            1                    13        0.035592      Fast Moving (<3 Months)           13                     0.076923                      0.076923
5692            371742       EER     2025-03-27      2025-03-27                1       17528.00            1                     4        0.010951      Fast Moving (<3 Months)            4                     0.250000                      0.250000

[5693 rows x 13 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.9.</b><b> Dealing with Outliers</b></u></p>

In [33]:
# Display top 5 largest values in the 'Total Sales Amount'.
df.nlargest(5, 'Total Sales Amount')

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type                   Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count   Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count  Customer Total Unique Items Overall     sin_month  cos_month
15204          9404144       2024-10-10               FXDW             Closed                  2556  AJM CO.,LTD.            102994       HBT   110283.00       210      End User  Transportation/Transport Machinery          Continue                PLC           PLC iQ-R    110283.0  2024     10        4         False           False            3       False            10    2024-10         23159430.00             0.00             0.000000         23159430.0                  0.00           110283.00  Enterprise (>50k)                 4.035666e+07                   388  104012.016469        1.333553e+08          False               False                     Loss                       0.0             12.750000                     1.421704                          54                                   54 -8.660254e-01        0.5
11209          7674880       2022-02-15               BQUM             Closed                  2335  AII CO.,LTD.            113965       HIH  1413556.58        16      End User                         Electronics          Continue              Robot           Robot FR   1840216.0  2022      2        1         False           False            1       False            15    2022-02         22616905.28        426659.42             0.231853         29443456.0            6826550.72          1413556.58  Enterprise (>50k)                 8.550804e+07                   707  120944.893126        2.401795e+08           True               False                     Loss                       0.0              3.041667                     1.517472                         276                                  566  8.660254e-01        0.5
15211          9404144       2024-10-10               FXDW             Closed                  2556  AJM CO.,LTD.            103510       HDW    27352.00       642      End User  Transportation/Transport Machinery          Continue                PLC           PLC iQ-R     27352.0  2024     10        4         False           False            3       False            10    2024-10         17559984.00             0.00             0.000000         17559984.0                  0.00            27352.00  Enterprise (>50k)                 8.336080e+07                   395  211039.988329        1.333553e+08          False               False                     Loss                       0.0             26.659574                     1.814264                          54                                   54 -8.660254e-01        0.5
5493           9007913       2024-04-23               FCWW             Closed                  1552  AEH CO.,LTD.            183883       CKJ    41239.00       200      End User                               Other          Continue                INV    INV E800 Nagoya     41239.0  2024      4        2         False           False            1       False            23    2024-04          8247800.00             0.00             0.000000          8247800.0                  0.00            41239.00  Enterprise (>50k)                 1.774081e+07                   145  122350.434138        4.091254e+07          False               False                     Loss                       1.0              4.891473                     1.103942                         101                                  153  8.660254e-01       -0.5
122021         8770980       2023-12-22               EQZH             Billed                  5005  AUN CO.,LTD.             20834       AQH     4029.00      2000      End User          Wholesale and Distribution          Continue               iQSS            Anywire      4335.0  2023     12        4         False           False            4       False            22    2023-12          8058000.00           306.00             0.070588          8670000.0             612000.00             4029.00  Enterprise (>50k)                 3.487419e+08                  6526   53438.851067        5.247132e+08           True               False                   Earned                       0.0            506.666667                     1.245120                        1065                                 1216 -2.449294e-16        1.0

In [34]:
# Apply percentile capping to numerical features.
cap_cols = ['Quantity', 'Total Sales Amount', 'Base Price']

for col in cap_cols:
    upper_limit = df[col].quantile(0.99)                # 99th percentile cutoff.
    lower_limit = df[col].quantile(0.001)               # Keep non-zero minimums.

    # Cap values beyond the 99th percentile.
    df[f'{col}_Capped'] = df[col].clip(lower=lower_limit, upper=upper_limit)

# Display row preserved.
print('Outlier capping complete. Row count preserved:', len(df))

df

Outlier capping complete. Row count preserved: 265070

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count  Customer Total Unique Items Overall     sin_month     cos_month  Quantity_Capped  Total Sales Amount_Capped  Base Price_Capped
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                       0.0              1.272966                     1.099698                           1                                    3 -2.449294e-16  1.000000e+00                1                    16103.0            16103.0
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                       0.0              5.454545                     0.854174                           2                                    3 -2.449294e-16  1.000000e+00                5                    14630.0             2926.0
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                     249.0              1.240566                     1.088854                           3                                    3 -8.660254e-01 -5.000000e-01                1                    16103.0            16103.0
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                       0.0              2.635659                     0.979929                           1                                   12  5.000000e-01 -8.660254e-01                2                     4052.0             2026.0
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                       0.0              6.283388                     1.033099                           2                                   12  5.000000e-01 -8.660254e-01                2                     4612.0             2306.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...                         ...                                  ...           ...           ...              ...                        ...                ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                       0.0              2.038610                     1.224468                           2                                    3  8.660254e-01  5.000000e-01                1                    63578.0            63578.0
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                       0.0              1.293750                     1.130720                           3                                    3  8.660254e-01  5.000000e-01                1                     9070.0             9070.0
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                       0.0              1.354167                     1.104637                           1                                    1  8.660254e-01  5.000000e-01                1                    42716.0            42716.0
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                       0.0              1.090909                     1.038609                           1                                    1  8.660254e-01  5.000000e-01                1                    16103.0            16103.0
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                       0.0              5.587687                     1.059810                           1                                    1  1.000000e+00  6.123234e-17                1                     2676.0             2676.0

[265070 rows x 49 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 2.10.</b><b> Save to a New Excel File</b></u></p>

In [36]:
# Save the cleaned data into the excel file.
df.to_excel('./excel/data_transformed_main.xlsx', index=False)
inventory_features.to_excel('./excel/inventory_transformed_main.xlsx', index=False)