# <u><b>Data Encoding (For Categorical Data)</b></u>

## <b style='color: yellow;'>0.</b> <u>Import Libraries</u>

In [1]:
import csv
import numpy as np
import pandas as pd
import openpyxl as op

# Force pandas to print all columns in a single line.
pd.set_option('display.width', 1000)                # Keeps lines from wrapping.
pd.set_option('display.max_columns', None)          # Displays every single column.

## <u>Load the data</u>

In [2]:
# Load the 'data_transformed_main.xlx' and 'inventory_transformed_main.xlsx' using pandas.
df_sales = pd.read_excel('./excel/data_transformed_main.xlsx')
df_inv = pd.read_excel('./excel/inventory_transformed_main.xlsx')
df_sales

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count  Customer Total Unique Items Overall     sin_month     cos_month  Quantity_Capped  Total Sales Amount_Capped  Base Price_Capped
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                         0              1.272966                     1.099698                           1                                    3 -2.449294e-16  1.000000e+00                1                    16103.0            16103.0
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                         0              5.454545                     0.854174                           2                                    3 -2.449294e-16  1.000000e+00                5                    14630.0             2926.0
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                       249              1.240566                     1.088854                           3                                    3 -8.660254e-01 -5.000000e-01                1                    16103.0            16103.0
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                         0              2.635659                     0.979929                           1                                   12  5.000000e-01 -8.660254e-01                2                     4052.0             2026.0
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                         0              6.283388                     1.033099                           2                                   12  5.000000e-01 -8.660254e-01                2                     4612.0             2306.0
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...                         ...                                  ...           ...           ...              ...                        ...                ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                         0              2.038610                     1.224468                           2                                    3  8.660254e-01  5.000000e-01                1                    63578.0            63578.0
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                         0              1.293750                     1.130720                           3                                    3  8.660254e-01  5.000000e-01                1                     9070.0             9070.0
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                         0              1.354167                     1.104637                           1                                    1  8.660254e-01  5.000000e-01                1                    42716.0            42716.0
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                         0              1.090909                     1.038609                           1                                    1  8.660254e-01  5.000000e-01                1                    16103.0            16103.0
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                         0              5.587687                     1.059810                           1                                    1  1.000000e+00  6.123234e-17                1                     2676.0             2676.0

[265070 rows x 49 columns]

In [3]:
df_inv

      Item Internal Id Item Code Last_Sale_Date First_Sale_Date  Total_Unit_Sold  Total_Revenue  Order_Count  Days_Since_Last_Sale  Years_Inactive          Inventory_Risk_Tier  Days_Active  Sales_Frequency_Ratio_Units  Sales_Frequency_Ratio_Orders
0                  111       AYV     2023-12-25      2023-11-22                3       12002.25            2                   462        1.264887        Slow Moving (1-2 yrs)          495                     0.006061                      0.004040
1                 2659       FXK     2022-10-04      2022-05-31                2       80652.00            2                   909        2.488706  High Aging Risk (2-3.5 yrs)         1035                     0.001932                      0.001932
2                 6199       FFU     2025-03-31      2021-04-02            11999    20535581.42          806                     0        0.000000      Fast Moving (<3 Months)         1459                     8.224126                      0.552433
3                 6200       FFZ     2025-03-03      2021-04-09              176      378297.00           90                    28        0.076660      Fast Moving (<3 Months)         1452                     0.121212                      0.061983
4                 6201       FGF     2025-03-26      2021-04-05              251     1361959.60          106                     5        0.013689      Fast Moving (<3 Months)         1456                     0.172390                      0.072802
...                ...       ...            ...             ...              ...            ...          ...                   ...             ...                          ...          ...                          ...                           ...
5688            368917       CJY     2025-03-17      2025-03-17                2      110084.00            1                    14        0.038330      Fast Moving (<3 Months)           14                     0.142857                      0.071429
5689            369018       CJN     2025-03-18      2025-03-18                1       35729.00            1                    13        0.035592      Fast Moving (<3 Months)           13                     0.076923                      0.076923
5690            369829       CJI     2025-03-18      2025-03-18                1       16380.00            1                    13        0.035592      Fast Moving (<3 Months)           13                     0.076923                      0.076923
5691            370438       CCV     2025-03-18      2025-03-18                1       17811.00            1                    13        0.035592      Fast Moving (<3 Months)           13                     0.076923                      0.076923
5692            371742       EER     2025-03-27      2025-03-27                1       17528.00            1                     4        0.010951      Fast Moving (<3 Months)            4                     0.250000                      0.250000

[5693 rows x 13 columns]

---

## <b style='color: yellow;'>3.</b> <u>Data Encoding (For Categorical Data)</u>

<ul style='font-size: 1.4em; line-height: 1.4;'>
    <li><b style='color: red;'>Step 3.1.</b> <b> Merge Two Data Together</b>
        <p style="font-size: 1em; margin-top: 8px; line-height: 1.4;">To make an enriched context for every transaction. Model learns whether an item was fast-moving or dead stock at the time of purchase. In addition, it avoids redundant encodings. Merging allows us to maintain a single encoding pipeline rather than managing two isolated datasets.</p>
    </li>
    <li><b style='color: red;'>Step 3.2.</b> <b> Apply Categorical Encodings</b>
        <ul style='line-height: 1.4;'>
            <li><b style='color: orange;'>Step 3.2.1.</b><b> Ordinal Ending (Preserve Clear Hierarchy)</b></li>
            <li><b style='color: orange;'>Step 3.2.2.</b><b> Frequency Encoding (For High-Cardinality IDs)</b></li>
            <li><b style='color: orange;'>Step 3.2.3.</b><b> One-Hot Encoding (For Low-Cardinality Nominal Categories)</b></li>
        </ul>
    </li>
    <li><b style='color: red;'>Step 3.3.</b> <b> Final Cleanup & Export to a New Excel File</b>
    </li>
</ul>

---

<p style='font-size: 1.4em;'><u><b style='color: red'>Step 3.1.</b> <b>Merge Two Data Together</u></b>

In [4]:
# Select key item-level features from inventory file to prevent column duplications.
inv_cols = [
    'Item Internal Id',
    'Days_Since_Last_Sale',
    'Inventory_Risk_Tier',
    'Sales_Frequency_Ratio_Units',
    'Sales_Frequency_Ratio_Orders'
]
df_inv_subset = df_inv[inv_cols]


# Merge Inventory Context into Sales Data.
df = pd.merge(df_sales, df_inv_subset, on='Item Internal Id', how='left')

# Fill any missing inventory tiers for rare unmapped items.
df['Inventory_Risk_Tier'] = df['Inventory_Risk_Tier'].fillna('Unknown')
df

        So Internal Id Sales Order Date Sales Order Number Sales Order Status  Customer Internal Id  Company Name  Item Internal Id Item Code  Base Price  Quantity Customer Type Fa Sub Industries Production Status Product Category 1 Product Category 2  List Price  Year  Month  Quarter  is_month_end  is_quarter_end  Day of Week  is_weekend  Day of Month Year-Month  Total Sales Amount  Discount Amount  Discount Percentage  Total Gross Value  Total Discount Value  Unit Selling Price    Order Size Tier  Customer Cumulative Revenue  Customer Order Count  Customer AOV  Customer Total LTV  is_discounted  is_zero_base_price Sales Order Status Group  Days Since Last Purchase  Product-Level Demand  Item Price Elasticity Ratio  Customer Unique Item Count  Customer Total Unique Items Overall     sin_month     cos_month  Quantity_Capped  Total Sales Amount_Capped  Base Price_Capped  Days_Since_Last_Sale            Inventory_Risk_Tier  Sales_Frequency_Ratio_Units  Sales_Frequency_Ratio_Orders
0              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.             57209       ICD     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2022     12        4         False           False            3       False             1    2022-12             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             46836.0          False               False                   Earned                         0              1.272966                     1.099698                           1                                    3 -2.449294e-16  1.000000e+00                1                    16103.0            16103.0                   392          Slow Moving (1-2 yrs)                     0.332419                      0.261138
1              8149886       2022-12-01               DDRW             Billed                   702  AAK CO.,LTD.            134587       ICE      2926.0         5      End User  Automobile Parts          Continue           Software            MELSOFT      4041.0  2022     12        4         False           False            3       False             1    2022-12             14630.0           1115.0             0.275922            20205.0                5575.0              2926.0    Large (10k-50k)                      30733.0                     2       15366.5             46836.0           True               False                   Earned                         0              5.454545                     0.854174                           2                                    3 -2.449294e-16  1.000000e+00                5                    14630.0             2926.0                   230  Normal Velocity (3-12 Months)                     0.124913                      0.022901
2              8529221       2023-08-07               ECRT             Billed                   702  AAK CO.,LTD.             16690       IBS     16103.0         1      End User  Automobile Parts       Discontinue           Software            MELSOFT     16103.0  2023      8        3         False           False            0       False             7    2023-08             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      46836.0                     3       15612.0             46836.0          False               False                   Earned                       249              1.240566                     1.088854                           3                                    3 -8.660254e-01 -5.000000e-01                1                    16103.0            16103.0                   321  Normal Velocity (3-12 Months)                     0.180880                      0.145805
3              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8100       BXQ      2026.0         2      End User       Engineering          Continue                INV         INV Others      2521.0  2021      5        2         False           False            2       False            12    2021-05              4052.0            495.0             0.196351             5042.0                 990.0              2026.0    Medium (1k-10k)                       4052.0                     1        4052.0            289756.0           True               False                   Earned                         0              2.635659                     0.979929                           1                                   12  5.000000e-01 -8.660254e-01                2                     4052.0             2026.0                     0        Fast Moving (<3 Months)                     0.237596                      0.090147
4              7216283       2021-05-12               AEHJ             Billed                   703  AAL CO.,LTD.              8240       BZC      2306.0         2      End User       Engineering          Continue                INV         INV Others      2498.0  2021      5        2         False           False            2       False            12    2021-05              4612.0            192.0             0.076861             4996.0                 384.0              2306.0    Medium (1k-10k)                       8664.0                     2        4332.0            289756.0           True               False                   Earned                         0              6.283388                     1.033099                           2                                   12  5.000000e-01 -8.660254e-01                2                     4612.0             2306.0                     0        Fast Moving (<3 Months)                     1.324863                      0.210852
...                ...              ...                ...                ...                   ...           ...               ...       ...         ...       ...           ...               ...               ...                ...                ...         ...   ...    ...      ...           ...             ...          ...         ...           ...        ...                 ...              ...                  ...                ...                   ...                 ...                ...                          ...                   ...           ...                 ...            ...                 ...                      ...                       ...                   ...                          ...                         ...                                  ...           ...           ...              ...                        ...                ...                   ...                            ...                          ...                           ...
265065         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.            109944       EBZ     63578.0         1      End User           Machine          Continue                HMI     GOT2000 Nagoya     63578.0  2025      2        1         False           False            1       False            11    2025-02             63578.0              0.0             0.000000            63578.0                   0.0             63578.0  Enterprise (>50k)                      89684.0                     2       44842.0             98754.0          False               False                   Earned                         0              2.038610                     1.224468                           2                                    3  8.660254e-01  5.000000e-01                1                    63578.0            63578.0                     0        Fast Moving (<3 Months)                     0.361644                      0.177397
265066         9644736       2025-02-11               GKKW             Billed                914931  DEX CO.,LTD.             84221       EBT      9070.0         1      End User           Machine          Continue                HMI         GOT Others      9070.0  2025      2        1         False           False            1       False            11    2025-02              9070.0              0.0             0.000000             9070.0                   0.0              9070.0    Medium (1k-10k)                      98754.0                     3       32918.0             98754.0          False               False                   Earned                         0              1.293750                     1.130720                           3                                    3  8.660254e-01  5.000000e-01                1                     9070.0             9070.0                     0        Fast Moving (<3 Months)                     0.141878                      0.109664
265067         9664318       2025-02-21               GLUN             Billed                921563  DEY CO.,LTD.             10785       CZW     42716.0         1      End User              Wood          Continue                PLC             PLC FX     44802.0  2025      2        1         False           False            4       False            21    2025-02             42716.0           2086.0             0.046560            44802.0                2086.0             42716.0    Large (10k-50k)                      42716.0                     1       42716.0             42716.0           True               False                   Earned                         0              1.354167                     1.104637                           1                                    1  8.660254e-01  5.000000e-01                1                    42716.0            42716.0                     0        Fast Moving (<3 Months)                     0.181311                      0.133891
265068         9673928       2025-02-27               GMLD             Billed                925313  DEZ CO.,LTD.            188347       ICF     16103.0         1      End User          Plastics          Continue           Software           Software     16103.0  2025      2        1         False           False            3       False            27    2025-02             16103.0              0.0             0.000000            16103.0                   0.0             16103.0    Large (10k-50k)                      16103.0                     1       16103.0             16103.0          False               False                   Earned                         0              1.090909                     1.038609                           1                                    1  8.660254e-01  5.000000e-01                1                    16103.0            16103.0                     0        Fast Moving (<3 Months)                     0.234801                      0.215234
265069         9689484       2025-03-05               GNJD             Billed                928079  DFA CO.,LTD.             10244       BGE      2676.0         1      End User   Food & Beverage          Continue                PLC             PLC FX      2676.0  2025      3        1         False           False            2       False             5    2025-03              2676.0              0.0             0.000000             2676.0                   0.0              2676.0    Medium (1k-10k)                       2676.0                     1        2676.0              2676.0          False               False                   Earned                         0              5.587687                     1.059810                           1                                    1  1.000000e+00  6.123234e-17                1                     2676.0             2676.0                     3        Fast Moving (<3 Months)                     2.052776                      0.367375

[265070 rows x 53 columns]

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 3.2.</b><b> Apply Categorical Encodings</b></u></p>

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 3.2.1.</b><b> Ordinal Encoding (Preserve Clear Hierarchy)</b></u></p>

In [5]:
# Mapping the 'Order Size Tier'.
order_tier_map = {
    'Small (<1k)': 1,
    'Medium (1k-10k)' : 2,
    'Large (10k-50k)': 3,
    'Enterprise (>50k)': 4
}

# Mapping the 'Inventory_Risk_Tier'.
inventory_risk_map = {
    "Fast Moving (<3 Months)": 1,
    "Normal Velocity (3-12 Months)": 2,
    "Slow Moving (1-2 yrs)": 3,
    "High Aging Risk (2-3.5 yrs)": 4,
    "Critical Risk! (>3.5 years)": 5,
    "Unknown": 0,
}

# Add column.
df['Order_Size_Tier_Encoded'] = (df['Order Size Tier'].map(order_tier_map).fillna(0))
df['Inventory_Risk_Tier_Encoded'] = (df['Inventory_Risk_Tier'].map(inventory_risk_map).fillna(0))
df

,So Internal Id,Sales Order Date,Sales Order Number,Sales Order Status,Customer Internal Id,Company Name,Item Internal Id,Item Code,Base Price,Quantity,Customer Type,Fa Sub Industries,Production Status,Product Category 1,Product Category 2,List Price,Year,Month,Quarter,is_month_end,is_quarter_end,Day of Week,is_weekend,Day of Month,Year-Month,Total Sales Amount,Discount Amount,Discount Percentage,Total Gross Value,Total Discount Value,Unit Selling Price,Order Size Tier,Customer Cumulative Revenue,Customer Order Count,Customer AOV,Customer Total LTV,is_discounted,is_zero_base_price,Sales Order Status Group,Days Since Last Purchase,Product-Level Demand,Item Price Elasticity Ratio,Customer Unique Item Count,Customer Total Unique Items Overall,sin_month,cos_month,Quantity_Capped,Total Sales Amount_Capped,Base Price_Capped,Days_Since_Last_Sale,Inventory_Risk_Tier,Sales_Frequency_Ratio_Units,Sales_Frequency_Ratio_Orders,Order_Size_Tier_Encoded,Inventory_Risk_Tier_Encoded
0,8149886,2022-12-01,DDRW,Billed,702,"AAK CO.,LTD.",57209,ICD,16103.0,1,End User,Automobile Parts,Discontinue,Software,MELSOFT,16103.0,2022,12,4,False,False,3,False,1,2022-12,16103.0,0.0,0.000000,16103.0,0.0,16103.0,Large (10k-50k),16103.0,1,16103.0,46836.0,False,False,Earned,0,1.272966,1.099698,1,3,-2.449294e-16,1.000000e+00,1,16103.0,16103.0,392,Slow Moving (1-2 yrs),0.332419,0.261138,3,3
1,8149886,2022-12-01,DDRW,Billed,702,"AAK CO.,LTD.",134587,ICE,2926.0,5,End User,Automobile Parts,Continue,Software,MELSOFT,4041.0,2022,12,4,False,False,3,False,1,2022-12,14630.0,1115.0,0.275922,20205.0,5575.0,2926.0,Large (10k-50k),30733.0,2,15366.5,46836.0,True,False,Earned,0,5.454545,0.854174,2,3,-2.449294e-16,1.000000e+00,5,14630.0,2926.0,230,Normal Velocity (3-12 Months),0.124913,0.022901,3,2
2,8529221,2023-08-07,ECRT,Billed,702,"AAK CO.,LTD.",16690,IBS,16103.0,1,End User,Automobile Parts,Discontinue,Software,MELSOFT,16103.0,2023,8,3,False,False,0,False,7,2023-08,16103.0,0.0,0.000000,16103.0,0.0,16103.0,Large (10k-50k),46836.0,3,15612.0,46836.0,False,False,Earned,249,1.240566,1.088854,3,3,-8.660254e-01,-5.000000e-01,1,16103.0,16103.0,321,Normal Velocity (3-12 Months),0.180880,0.145805,3,2
3,7216283,2021-05-12,AEHJ,Billed,703,"AAL CO.,LTD.",8100,BXQ,2026.0,2,End User,Engineering,Continue,INV,INV Others,2521.0,2021,5,2,False,False,2,False,12,2021-05,4052.0,495.0,0.196351,5042.0,990.0,2026.0,Medium (1k-10k),4052.0,1,4052.0,289756.0,True,False,Earned,0,2.635659,0.979929,1,12,5.000000e-01,-8.660254e-01,2,4052.0,2026.0,0,Fast Moving (<3 Months),0.237596,0.090147,2,1
4,7216283,2021-05-12,AEHJ,Billed,703,"AAL CO.,LTD.",8240,BZC,2306.0,2,End User,Engineering,Continue,INV,INV Others,2498.0,2021,5,2,False,False,2,False,12,2021-05,4612.0,192.0,0.076861,4996.0,384.0,2306.0,Medium (1k-10k),8664.0,2,4332.0,289756.0,True,False,Earned,0,6.283388,1.033099,2,12,5.000000e-01,-8.660254e-01,2,4612.0,2306.0,0,Fast Moving (<3 Months),1.324863,0.210852,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265065,9644736,2025-02-11,GKKW,Billed,914931,"DEX CO.,LTD.",109944,EBZ,63578.0,1,End User,Machine,Continue,HMI,GOT2000 Nagoya,63578.0,2025,2,1,False,False,1,False,11,2025-02,63578.0,0.0,0.000000,63578.0,0.0,63578.0,Enterprise (>50k),89684.0,2,44842.0,98754.0,False,False,Earned,0,2.038610,1.224468,2,3,8.660254e-01,5.000000e-01,1,63578.0,63578.0,0,Fast Moving (<3 Months),0.361644,0.177397,4,1
265066,9644736,2025-02-11,GKKW,Billed,914931,"DEX CO.,LTD.",84221,EBT,9070.0,1,End User,Machine,Continue,HMI,GOT Others,9070.0,2025,2,1,False,False,1,False,11,2025-02,9070.0,0.0,0.000000,9070.0,0.0,9070.0,Medium (1k-10k),98754.0,3,32918.0,98754.0,False,False,Earned,0,1.293750,1.130720,3,3,8.660254e-01,5.000000e-01,1,9070.0,9070.0,0,Fast Moving (<3 Months),0.141878,0.109664,2,1
265067,9664318,2025-02-21,GLUN,Billed,921563,"DEY CO.,LTD.",10785,CZW,42716.0,1,End User,Wood,Continue,PLC,PLC FX,44802.0,2025,2,1,False,False,4,False,21,2025-02,42716.0,2086.0,0.046560,44802.0,2086.0,42716.0,Large (10k-50k),42716.0,1,42716.0,42716.0,True,False,Earned,0,1.354167,1.104637,1,1,8.660254e-01,5.000000e-01,1,42716.0,42716.0,0,Fast Moving (<3 Months),0.181311,0.133891,3,1
265068,9673928,2025-02-27,GMLD,Billed,925313,"DEZ CO.,LTD.",188347,ICF,16103.0,1,End User,Plastics,Continue,Software,Software,16103.0,2025,2,1,False,False,3,False,27,2025-02,16103.0,0.0,0.000000,16103.0,0.0,16103.0,Large (10k-50k),16103.0,1,16103.0,16103.0,False,False,Earned,0,1.090909,1.038609,1,1,8.660254e-01,5.000000e-01,1,16103.0,16103.0,0,Fast Moving (<3 Months),0.234801,0.215234,3,1
265069,9689484,2025-03-05,GNJD,Billed,928079,"DFA CO.,LTD.",10244,BGE,2676.0,1,End User,Food & Beverage,Continue,PLC,PLC FX,2676.0,2025,3,1,False,False,2,False,5,2025-03,2676.0,0.0,0.000000,2676.0,0.0,2676.0,Medium (1k-10k),2676.0,1,2676.0,2676.0,False,False,Earned,0,5.587687,1.059810,1,1,1.000000e+00,6.123234e-17,1,2676.0,2676.0,3,Fast Moving (<3 Months),2.052776,0.367375,2,1

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 3.2.2.</b><b> Frequency Encoding (For High-Cardinality IDs)</b></u></p>

In [6]:
df['Customer_Order_Frequency'] = df.groupby('Customer Internal Id')['Customer Internal Id'].transform('count')
df['Item_Order_Frequency'] = df.groupby('Item Code')['Item Code'].transform('count')

<p style='font-size: 1.4em;'><u><b style='color: orange;'>Step 3.2.3.</b><b> One-Hot Encoding (For Low-Cardinality Nominal Categories)</b></u></p>

In [7]:
ohe_col = [
    'Customer Type',
    'Production Status',
    'Sales Order Status Group',
    'Product Category 1',
    'Fa Sub Industries'
]

# Drop original nominal text columns and replace with dummy columns.
df_encode = pd.get_dummies(df, columns=ohe_col, drop_first=True, dtype=int)
df_encode

,So Internal Id,Sales Order Date,Sales Order Number,Sales Order Status,Customer Internal Id,Company Name,Item Internal Id,Item Code,Base Price,Quantity,Product Category 2,List Price,Year,Month,Quarter,is_month_end,is_quarter_end,Day of Week,is_weekend,Day of Month,Year-Month,Total Sales Amount,Discount Amount,Discount Percentage,Total Gross Value,Total Discount Value,Unit Selling Price,Order Size Tier,Customer Cumulative Revenue,Customer Order Count,Customer AOV,Customer Total LTV,is_discounted,is_zero_base_price,Days Since Last Purchase,Product-Level Demand,Item Price Elasticity Ratio,Customer Unique Item Count,Customer Total Unique Items Overall,sin_month,cos_month,Quantity_Capped,Total Sales Amount_Capped,Base Price_Capped,Days_Since_Last_Sale,Inventory_Risk_Tier,Sales_Frequency_Ratio_Units,Sales_Frequency_Ratio_Orders,Order_Size_Tier_Encoded,Inventory_Risk_Tier_Encoded,Customer_Order_Frequency,Item_Order_Frequency,Customer Type_VIP,Production Status_Discontinue,Production Status_To Be Advised,Sales Order Status Group_Loss,Sales Order Status Group_On going,Product Category 1_Geared Motor,Product Category 1_HMI,Product Category 1_INV,Product Category 1_LVS,Product Category 1_MEATH,Product Category 1_MEE,Product Category 1_MELIPC,Product Category 1_PLC,Product Category 1_Robot,Product Category 1_SC,Product Category 1_SV,Product Category 1_Scada,Product Category 1_Software,Product Category 1_Tension Controller,Product Category 1_iQSS,Fa Sub Industries_Agriculture / Farming,Fa Sub Industries_Automation,Fa Sub Industries_Automobile,Fa Sub Industries_Automobile Parts,Fa Sub Industries_Biotechnology,Fa Sub Industries_Built in Equipment,Fa Sub Industries_Chemicals,Fa Sub Industries_Consumer Product,Fa Sub Industries_Corporate,Fa Sub Industries_Design Office,Fa Sub Industries_Developer,Fa Sub Industries_Education,Fa Sub Industries_Electronic Parts,Fa Sub Industries_Electronics,Fa Sub Industries_Energy,Fa Sub Industries_Engineering,Fa Sub Industries_Equipment Trading Company,Fa Sub Industries_Factory/Warehouse,Fa Sub Industries_Food & Beverage,Fa Sub Industries_Foods(Food and Packaging Machinery),Fa Sub Industries_General Contractor,Fa Sub Industries_General Machinery,Fa Sub Industries_Glass,Fa Sub Industries_Government,Fa Sub Industries_Healthcare,Fa Sub Industries_Healthcare and Pharmaceuticals,Fa Sub Industries_Household Equipment Parts,Fa Sub Industries_Household and Personal Care,Fa Sub Industries_IT & Software,Fa Sub Industries_Industrial Building,Fa Sub Industries_Industrial Machinery,Fa Sub Industries_Information SI,Fa Sub Industries_Instrumentation SI,Fa Sub Industries_Lithium Ion Battery,Fa Sub Industries_M&E Contractor,Fa Sub Industries_Machine,Fa Sub Industries_Medical Devices,Fa Sub Industries_Medical/Medicine Machinery,Fa Sub Industries_Metal,Fa Sub Industries_Motorcycle,Fa Sub Industries_Other,Fa Sub Industries_Packaging,Fa Sub Industries_Paper,Fa Sub Industries_Petroleum,Fa Sub Industries_Pharmaceutical/Medical Engineering,Fa Sub Industries_Pharmaceuticals,Fa Sub Industries_Plastics,Fa Sub Industries_Power company,Fa Sub Industries_Printed Circuit Board,Fa Sub Industries_Real Estate and Construction,Fa Sub Industries_Residental Market,Fa Sub Industries_Robotic,Fa Sub Industries_Rubber,Fa Sub Industries_Semiconductor,Fa Sub Industries_Software Vendor,Fa Sub Industries_Solar Cell,Fa Sub Industries_Steel(Including Steel SI),Fa Sub Industries_Subcontractor,"Fa Sub Industries_Synthetic Resin,Rubber",Fa Sub Industries_Telecommunications,Fa Sub Industries_Textile,Fa Sub Industries_Tooling Machinery,Fa Sub Industries_Trading Company,Fa Sub Industries_Transportation and Storage,Fa Sub Industries_Transportation/Transport Machinery,Fa Sub Industries_Water Treatment and Utilities,Fa Sub Industries_Wholesale and Distribution,Fa Sub Industries_Wood
0,8149886,2022-12-01,DDRW,Billed,702,"AAK CO.,LTD.",57209,ICD,16103.0,1,MELSOFT,16103.0,2022,12,4,False,False,3,False,1,2022-12,16103.0,0.0,0.000000,16103.0,0.0,16103.0,Large (10k-50k),16103.0,1,16103.0,46836.0,False,False,0,1.272966,1.099698,1,3,-2.449294e-16,1.000000e+00,1,16103.0,16103.0,392,Slow Moving (1-2 yrs),0.332419,0.261138,3,3,3,381,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,8149886,2022-12-01,DDRW,Billed,702,"AAK CO.,LTD.",134587,ICE,2926.0,5,MELSOFT,4041.0,2022,12,4,False,False,3,False,1,2022-12,14630.0,1115.0,0.275922,20205.0,5575.0,2926.0,Large (10k-50k),30733.0,2,15366.5,46836.0,True,False,0,5.454545,0.854174,2,3,-2.449294e-16,1.000000e+00,5,14630.0,2926.0,230,Normal Velocity (3-12 Months),0.124913,0.022901,3,2,3,33,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,8529221,2023-08-07,ECRT,Billed,702,"AAK CO.,LTD.",16690,IBS,16103.0,1,MELSOFT,16103.0,2023,8,3,False,False,0,False,7,2023-08,16103.0,0.0,0.000000,16103.0,0.0,16103.0,Large (10k-50k),46836.0,3,15612.0,46836.0,False,False,249,1.240566,1.088854,3,3,-8.660254e-01,-5.000000e-01,1,16103.0,16103.0,321,Normal Velocity (3-12 Months),0.180880,0.145805,3,2,3,212,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,7216283,2021-05-12,AEHJ,Billed,703,"AAL CO.,LTD.",8100,BXQ,2026.0,2,INV Others,2521.0,2021,5,2,False,False,2,False,12,2021-05,4052.0,495.0,0.196351,5042.0,990.0,2026.0,Medium (1k-10k),4052.0,1,4052.0,289756.0,True,False,0,2.635659,0.979929,1,12,5.000000e-01,-8.660254e-01,2,4052.0,2026.0,0,Fast Moving (<3 Months),0.237596,0.090147,2,1,13,129,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,7216283,2021-05-12,AEHJ,Billed,703,"AAL CO.,LTD.",8240,BZC,2306.0,2,INV Others,2498.0,2021,5,2,False,False,2,False,12,2021-05,4612.0,192.0,0.076861,4996.0,384.0,2306.0,Medium (1k-10k),8664.0,2,4332.0,289756.0,True,False,0,6.283388,1.033099,2,12,5.000000e-01,-8.660254e-01,2,4612.0,2306.0,0,Fast Moving (<3 Months),1.324863,0.210852,2,1,13,307,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265065,9644736,2025-02-11,GKKW,Billed,914931,"DEX CO.,LTD.",109944,EBZ,63578.0,1,GOT2000 Nagoya,63578.0,2025,2,1,False,False,1,False,11,2025-02,63578.0,0.0,0.000000,63578.0,0.0,63578.0,Enterprise (>50k),89684.0,2,44842.0,98754.0,False,False,0,2.038610,1.224468,2,3,8.660254e-01,5.000000e-01,1,63578.0,63578.0,0,Fast Moving (<3 Months),0.361644,0.177397,4,1,3,259,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
265066,9644736,2025-02-11,GKKW,Billed,914931,"DEX CO.,LTD.",84221,EBT,9070.0,1,GOT Others,9070.0,2025,2,1,False,False,1,False,11,2025-02,9070.0,0.0,0.000000,9070.0,0.0,9070.0,Medium (1k-10k),98754.0,3,32918.0,98754.0,False,False,0,1.293750,1.130720,3,3,8.660254e-01,5.000000e-01,1,9070.0,9070.0,0,Fast Moving (<3 Months),0.141878,0.109664,2,1,3,160,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
265067,9664318,2025-02-21,GLUN,Billed,921563,"DEY CO.,LTD.",10785,CZW,42716.0,1,PLC FX,44802.0,2025,2,1,False,False,4,False,21,2025-02,42716.0,2086.0,0.046560,44802.0,2086.0,42716.0,Large (10k-50k),42716.0,1,42716.0,42716.0,True,False,0,1.354167,1.104637,1,1,8.660254e-01,5.000000e-01,1,42716.0,42716.0,0,Fast Moving (<3 Months),0.181311,0.133891,3,1,1,192,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
265068,9673928,2025-02-27,GMLD,Billed,925313,"DEZ CO.,LTD.",188347,ICF,16103.0,1,Software,16103.0,2025,2,1,False,False,3,False,27,2025-02,16103.0,0.0,0.000000,16103.0,0.0,16103.0,Large (10k-50k),16103.0,1,16103.0,16103.0,False,False,0,1.090909,1.038609,1,1,8.660254e-01,5.000000e-01,1,16103.0,16103.0,0,Fast Moving (<3 Months),0.234801,0.215234,3,1,1,308,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
265069,9689484,2025-03-05,GNJD,Billed,928079,"DFA CO.,LTD.",10244,BGE,2676.0,1,PLC FX,2676.0,2025,3,1,False,False,2,False,5,2025-03,2676.0,0.0,0.000000,2676.0,0.0,2676.0,Medium (1k-10k),2676.0,1,2676.0,2676.0,False,False,0,5.587687,1.059810,1,1,1.000000e+00,6.123234e-17,1,2676.0,2676.0,3,Fast Moving (<3 Months),2.052776,0.367375,2,1,1,536,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

---

<p style='font-size: 1.4em;'><u><b style='color: red;'>Step 3.3.</b><b> Final Cleanup & Export to a New Excel File</b></u></p>

In [8]:
# Drop raw string/date columns not usable directly by machine learning algorithms
columns_to_drop = [
    "Sales Order Status",
    "Company Name",
    "Product Category 2",
    "Year-Month",
    "Order Size Tier",
    "Inventory_Risk_Tier",
]

df_final = df_encode.drop(columns=[c for c in columns_to_drop if c in df_encode.columns])
df_final.to_excel('./excel/final_dataset_main.xlsx', index=False)
df_final.to_csv('./excel/final_dataset_main.csv', index=False)